import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../common-utils/globals.css";
import Link from "next/link";
import MainHeader from "@/components/main-header/main-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container-none min-h-screen ${inter.className}`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
